from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

with open("requirements.txt", "r", encoding="utf-8") as fh:
    requirements = fh.read().splitlines()

setup(
    name="staticflow",
    version="0.1.0",
    author="Your Name",
    author_email="your.email@example.com",
    description="Static site generator with block editor support",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/staticflow",
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    install_requires=[
        "markdown>=3.4.0",
        "jinja2>=3.1.0",
        "pyyaml>=6.0",
        "watchdog>=2.1.0",
        "click>=8.1.0",
        "python-frontmatter>=1.0.0",
        "bleach>=6.0.0",
        "pymdown-extensions>=10.0.0",
        "python-slugify>=8.0.0",
        "beautifulsoup4>=4.12.0",
        "lxml>=4.9.0",
        "requests>=2.31.0",
        "aiohttp>=3.8.0",
        "aiofiles>=23.0.0",
        "python-multipart>=0.0.6",
        "websockets>=11.0.0",
        "rich>=13.0.0",
        "typer>=0.9.0",
        "pydantic>=2.0.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.23.0",
        "python-dotenv>=1.0.0",
        "cryptography>=41.0.0",
        "bcrypt>=4.0.0",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "python-magic>=0.4.27",
        "pillow>=10.0.0",
        "markupsafe>=2.1.0",
        "html5lib>=1.1",
        "cachetools>=5.3.0",
        "diskcache>=5.6.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "pytest-asyncio>=0.21.0",
            "pytest-mock>=3.11.0",
            "black>=23.7.0",
            "isort>=5.12.0",
            "mypy>=1.5.0",
            "flake8>=6.1.0",
            "pylint>=2.17.0",
            "bandit>=1.7.0",
            "safety>=2.3.0",
            "pre-commit>=3.3.0",
            "mkdocs>=1.5.0",
            "mkdocs-material>=9.2.0",
            "mkdocstrings>=0.22.0",
            "mkdocstrings-python>=0.8.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "staticflow=staticflow.cli:cli",
        ],
    },
    package_data={
        "staticflow": [
            "admin/static/dist/*",
            "admin/static/css/*",
            "admin/templates/*",
            "core/*",
            "utils/*",
            "cli/*",
            "deploy/*",
            "plugins/*",
            "themes/*",
            "tests/*",
        ],
    },
) 