# Site Information
site_name = "My Tech Blog"
base_url = "https://blog.example.com"
description = "A blog about technology and programming"
author = "John Doe"
language = "en"

# Build Settings
content_dir = "content"
output_dir = "public"
static_dir = "static"

# Template Settings
template_dir = "templates"
default_template = "post.html"

# Blog Settings
posts_per_page = 10
date_format = "%Y-%m-%d"
excerpt_length = 200

# Social Media
[social]
twitter = "@johndoe"
github = "johndoe"
linkedin = "john-doe"

# Analytics
[analytics]
google_analytics = "UA-XXXXXXXX-X"

# Cache Settings
[cache]
enabled = true
directory = ".cache"
ttl = 3600  # 1 hour

# SEO Settings
[seo]
meta_title = "{title} - {site_name}"
meta_description = "{excerpt}"
keywords = ["technology", "programming", "python", "web development"]

# Plugin Settings
[plugins]
syntax_highlight = true
table_of_contents = true
reading_time = true 