@startuml
|Разработчик|
start
:Инициализировать проект;

|Движок|
:Загрузить конфигурацию;
:Настроить пути;
:Загрузить тему;
:Загрузить шаблоны;
:Инициализировать кэш;

|Разработчик|
if (Использовать админку?) then (да)
    |Админка|
    :Открыть редактор;
    repeat
        |Редактор|
        :Проверить кэш предпросмотра;
        if (Кэш найден?) then (да)
            :Использовать кэшированный предпросмотр;
        else (нет)
            :Загрузить содержимое страницы;
            :Сохранить предпросмотр в кэш;
        endif
        :Редактировать страницу;
        :Сохранить изменения;
        |Страница|
        :Добавить в историю изменений;
        |Редактор|
        :Показать предпросмотр;
        :Сохранить предпросмотр в кэш;
        
        if (Просмотреть историю?) then (да)
            |Страница|
            :Получить список версий;
            |Редактор|
            :Выбрать версию для отката;
            |Страница|
            :Откатить к выбранной версии;
            |Редактор|
            :Показать предпросмотр;
        endif
    repeat while (Продолжить редактирование?) is (да)
else (нет)
    |Разработчик|
    :Создать файл контента;
    note right
        Поддерживаемые форматы:
        * Markdown (.md)
        * HTML (.html)
        * ReStructuredText (.rst)
        * AsciiDoc (.adoc)
        * и другие...
    end note
    :Добавить файл в проект;
endif

|Разработчик|
:Запустить сборку;

|Движок|
:Начать процесс сборки;

|Сайт|
:Загрузить все страницы;

repeat
    |Страница|
    :Получить расширение файла;
    |ПарсерМенеджер|
    :Проверить наличие парсера для расширения;
    if (Парсер найден?) then (да)
        :Получить парсер;
        |Парсер|
        :Разобрать содержимое;
        :Извлечь метаданные;
    else (нет)
        |ПарсерМенеджер|
        :Вывести ошибку в консоль;
        note right
            "Парсер для расширения {расширение} не найден.
            Пожалуйста, добавьте парсер для этого формата."
        end note
        |Разработчик|
        :Добавить парсер для формата;
        |ПарсерМенеджер|
        :Зарегистрировать новый парсер;
        |Парсер|
        :Разобрать содержимое;
        :Извлечь метаданные;
    endif
repeat while (Есть еще страницы?)

|Плагины|
:Обработать весь сайт;

|Движок|
:Применить тему;

repeat
    |Страница|
    |Кэш|
    :Проверить наличие кэша;
    if (Кэш найден?) then (да)
        :Проверить срок действия;
        if (Кэш действителен?) then (да)
            :Использовать кэшированное содержимое;
        else (нет)
            :Удалить устаревший кэш;
            :Отрендерить шаблон;
            |Плагины|
            :Обработать контент;
            |Кэш|
            :Сохранить в кэш;
        endif
    else (нет)
        :Отрендерить шаблон;
        |Плагины|
        :Обработать контент;
        |Кэш|
        :Сохранить в кэш;
    endif
    
    |Плагины|
    :Обработать страницу;
repeat while (Есть еще страницы?) is (да)

|Движок|
:Копировать статические файлы;

|Разработчик|
if (Нужна публикация?) then (да)
    |Деплой|
    :Настроить параметры публикации;
    :Отправить на GitHub Pages;
    :Проверить статус публикации;
else (нет)
    |Движок|
    :Завершить сборку;
endif
-[#black]->
|Движок|
:Очистить ресурсы;
:Очистить кэш;

|Разработчик|
stop

@enduml