site_name = "demo"
base_url = "http://localhost:8000"
description = "A new StaticFlow site"
author = ""
language = "en"

# Directories
source_dir = "content"
template_dir = "templates"
static_dir = "static"
output_dir = "public"
output_path = ""  # Убираем поддиректорию pages из пути вывода

# Default settings
default_template = "base.html"
