# Site information
site_name = ""  # Will be set to project name
base_url = "http://localhost:8000"
description = "A new StaticFlow site"
author = ""
language = "ru"

# Directories
source_dir = "content"
template_dir = "templates"
static_dir = "static"
static_url = "/static"
output_dir = "public"

# Default settings
default_template = "page.html"

# Syntax highlighting settings
[syntax_highlight]
style = "monokai"  # Available options: "monokai", "default", "vs", "xcode", "colorful", "dracula", "github", etc.